# A workflow is called by workflow Push and runs checkout action

name: Call on new commit

on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
      is_workflow_call:
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      commit-sha:
        required: true
        type: string
    
jobs:
  call-on-new-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - run: echo "is workflow call ${{ inputs.is_workflow_call }}" 
      - uses: ./.github/actions/validate-access
        if: ${{ inputs.is_workflow_call }}
        with:
          admin-only: true
          image-path: oci/mock-default
          github-token: ${{ secrets.ORG_READ_TOKEN }}
