# A workflow is called by workflow Push and runs checkout action

name: Call on new commit

on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
  workflow_dispatch:
    
jobs:
  call-on-new-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
